version: "3"
services: 
  my_image:
    build: 
        context: ./
    image: muhos-echo-server:latest
  echoserver:
    image: muhos-echo-server:latest
    command: python3 -u echo-server.py
    ports:
      - "5001:5001"
